-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE
-- OR REPLACE VIEW "public"."orders_is_valid" AS
-- SELECT * FROM "orders"
-- WHERE "orders"."isValid" = true;
