on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn test

  storybook:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: "./packages/next-app"

  varcel-deploy-preview:
    needs: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: vercel pull --token ${{ secrets.VERCEL_TOKEN }} -y
      - run: yarn build-vercel
      - uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prebuilt"

  varcel-deploy-production:
    # TODO: update after fixing error
    # needs: [setup, lint, test]
    needs: [setup]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: vercel pull --token ${{ secrets.VERCEL_TOKEN }} -y
      - run: yarn build-vercel --prod
      - uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prebuilt --prod"
