name: Firebase Deploy
on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x.x
      - run: yarn
      - run: yarn build
      - run: yarn firebase use kaguraswap-prod --token=${{ secrets.FIREBASE_TOKEN }}
      - run: yarn firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
